services:
  - postgresql

env:
  - NODE_ENV=test

install:
  - npm install
  - npm uninstall -g typescript # We should rely only on the locally installed typescript

before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';" -U postgres

language: node_js
node_js:
  - "7"
  - "8"
  - "9"

script:
  - npm run server:lint
  - set -e
  - npm run server:init
  - npm run server:test