services:
  - postgresql

env:
  - NODE_ENV=test

install:
  - npm install

before_script:
  # - psql -c "CREATE DATABASE conductors-spy-test;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';" -U postgres
  - npm install -g gulp-cli

language: node_js
node_js:
  - "7"
  - "8"

script:
  - npm run db:test:recreate
  - npm run db:test:migrate
  - npm run server:lint
  - npm run server:build
  - npm run server:test
  - npm run server:start